export const text_default = "text text_type_main-default";
export const text_large = "text text_type_main-large";
export const text_medium = "text text_type_main-medium";
export const text_small = "text text_type_main-small";
export const text_inactive = "text text_type_main-default text_color_inactive";
export const text_inactive_medium = "text text_type_main-medium text_color_inactive";
export const digits_default = "text text_type_digits-default" 
export const digits_medium = "text text_type_digits-medium";
export const digits_large = "text text_type_digits-large";